### ISSUE TITLE
Feature request: Support some way to comment Markdown

### ISSUE THREAD

**Issue by mimshwright** [remarkjs/react-markdown#142]
While there is no common format for using comments in Markdown source code, some transpilers will ignore one of these two syntaxes:

`<!-- HTML-style comment -->`

`[//]: Footnote style comment`

However,  these currently render as escaped `<Html>` and `<a>`. 

Is that something you would consider adding?

**Comment by kromit** [comment]
HTML style comments were working in 2.x but are escaped in 3.x

**Comment by ivan-kleshnin** [comment]
Is there a way to escape MD special symbols.

Something like

```
\*not an emphasis but an asterisk here...
```

**Comment by ChristianMurphy** [comment]
HTML comments work, you can try them it in the playground https://remarkjs.github.io/react-markdown/

**Comment by pgraham** [comment]
Hi, I've just tried HTML style comments in the playground and they are not working:

<img width="1165" alt="Screen Shot 2022-02-23 at 11 03 44 AM" src="https://user-images.githubusercontent.com/483277/155358570-064bd647-d4fb-4ba6-adda-cb9aaaeaf856.png">

Is this the expected behaviour? Is there a different style of comment that can be used?

**Comment by ChristianMurphy** [comment]
It is expected, the `rehype-raw` option in the playground switches the behavior.
How to setup `rehype-raw` locally is documented in the readme as well https://github.com/remarkjs/react-markdown#appendix-a-html-in-markdown
