### ISSUE TITLE
Adding my own node

### ISSUE THREAD

**Issue by RT-TL** [remarkjs/react-markdown#249]
Thanks for building this awesome library! 

I want to add a new node to the available markdown elements. In particular I would like to add an underline-syntax (and maybe a few more later). I assume that the "plugin" functionality is  what I should use but I could not understand how to use it.

Can you help me in understanding if this is the purpose of the plugin and maybe provide an example? I would be happy to create a proposal for an improved readme file.

**Comment by el1f** [comment]
Since the focus of this lib is to provide a React component to render markdown I think looking for underlined text and such is gonna be quite difficult. Markdown as a language is a markup language and as such isn't that concerned on how the text actually looks, rather on providing tools to be semantically meaningful. Markdown usually only comes with **bold** and _italics_ since they are just two different levels of **emphasis**. It's the job of the stylesheet to then give them a graphical look, potentially you could target the `strong` tags created by the default renderer when wrapping words in ** characters and change their stylesheet to display an underlined text, or even override the default renderer for one of the blocks you're less likely to use and change it's rendering method to use a `span` with a custom class applied to it since the old `<u>` "underlined" tag was deprecated back with the introduction of HTML5.

**Comment by spech66** [comment]
Activating underline works with:

```
import * as Markdown from "react-markdown";
...
Markdown.renderers.underline = "u";
```

although this is not a very clean way of doing this.

**Comment by ChristianMurphy** [comment]
@RT-TL there is documentation for creating remark plugins at https://unifiedjs.com/learn/
