### ISSUE TITLE
HTML parser: `Cannot read property 'children' of undefined`

### ISSUE THREAD

**Issue by AlanLes** [remarkjs/react-markdown#345]
There's an error, if I try _to markdown_ text like this:

```
only a closing tag in new line
</dd>
like this
```

The whole app crashes.

(it crashes also your demo page: https://rexxars.github.io/react-markdown/)

**Comment by ChristianMurphy** [comment]
This will be resolved by #428

**Comment by ChristianMurphy** [comment]
In general though it is a good idea to use valid HTML.

**Comment by wooorm** [comment]
I believe this may be fixed on 5.0.0, [with this change](https://github.com/remarkjs/react-markdown/commit/22a5e49ae9dde84257d043f033d1b640b78c7b34#diff-e48a0b02aa7a8f65a453b849e7345933ee0072fb6d0c2a109c83f43cc8fae8c6). Could someone confirm whether that works? Otherwise it’s just the HTML parser being funky and the plan is for that to be replaced next major.

**Comment by wooorm** [comment]
This should be solved by landing GH-563 today, which will soon be released in v6.0.0!
