### ISSUE TITLE
Help with definition list?

### ISSUE THREAD

**Issue by limitlessloop** [remarkjs/react-markdown#409]
Hi, I'm trying to add support for definition lists using the `remark-deflist` plugin.

I don't think it' renders the HTML so I've had to render it myself.

This is what I have so far:

```
Term 1

: Definition 1
```

```js
function DefinitionList(props) {
	return (
		<dl>
			{props.children}
		</dl>
	)
}

function DefinitionTerm(props) {
	return (
		<dt>
			{props.children}
		</dt>
	)
}

function DefinitionDetails(props) {
	return (
		<dd>
			{props.children}
		</dd>
	)
}

<ReactMarkdown source={input.value} renderers={{ definitionList: DefinitionList, descriptionlist: DefinitionList, descriptionterm: DefinitionTerm, descriptiondetails: DefinitionDetails }} plugins={[deflist]}
```

Which results in

```html
<p>
  <dl>
    <dt>Term 1</dt>
    <dd>Definition 1</dd>
  </dl>
</p>
```

There are a couple of issues.

1. The primary issue is that it's wrapping the definition list in a paragraph tag, I'm not sure how to prevent this.
2. It wants both `definitionList` and `descriptionList` to be defined, I'm not sure why this is.
3. It's pretty ugly, can anyone suggest some ways to tidy it up a bit?

Many thanks.

**Comment by ChristianMurphy** [comment]
The plugin itself is adding the paragraph https://github.com/Symbitic/remark-plugins/blob/42fe314ed28647a119c3bc4b295c875e60940734/packages/remark-deflist/src/index.js#L31-L32

to unwrap it you'll probably want another plugin, something like https://github.com/remarkjs/remark-unwrap-images, but targeting deflist instead of image.
