### ISSUE TITLE
Allow some HTML tags

### ISSUE THREAD

**Issue by lukas1994** [remarkjs/react-markdown#414]
I'd like to allow some HTML tags (e.g. <img>) but I'm worried about XSS attacks. How can I make sure that using `react-markdown/with-html` is safe?

**Comment by rexxars** [comment]
The readme contains some info on this. Totally preventing XSS attacks is a very hard problem, so I've left that outside the scope of react-markdown.  The example below disallows script tags, for instance, but there are still plenty of other things you want to guard for - `href` with javascript in them, event handlers like `on...`... You're probably best off explicitly allowing things instead of _disallowing_ things. For instance, allow `strong` nodes, but only if they don't have any attributes, or only a specific set of attributes.

```js
const ReactMarkdown = require('react-markdown')
const htmlParser = require('react-markdown/plugins/html-parser')

// See https://github.com/aknuds1/html-to-react#with-custom-processing-instructions
// for more info on the processing instructions
const parseHtml = htmlParser({
  isValidNode: node => node.type !== 'script',
  processingInstructions: [/* ... */]
})

<ReactMarkdown
  source={markdown}
  escapeHtml={false}
  astPlugins={[parseHtml]}
/>
```
