### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by lxfu1** [remarkjs/react-markdown#431]
'react-markdown/plugins/html-parser' have a RegExp '/[^\0-\x7F]/gu' is not support IE11。

**Comment by ChristianMurphy** [comment]
IE comparability in general is being discussed at https://github.com/rexxars/react-markdown/issues/359

Your specific example `/[^\0-\x7F]/gu` doesn't appear in the codebase. https://github.com/rexxars/react-markdown/search?q=%2F%5B%5E%5C0-%5Cx7F%5D%2Fgu&type=Code
The issue is likely coming from a different package.
