### ISSUE TITLE
Use GH releases

### ISSUE THREAD

**Issue by wooorm** [remarkjs/react-markdown#481]
### Subject of the feature

Changelog file in source

### Problem

GH has a feature for this which, which some folks will find anyway. Which works fine with stuff like dependabot.
The problem is that a changelog is based git commits, but inside Git. Having it outside of Git helps.

**Comment by ChristianMurphy** [comment]
I'm not sure I follow the issue here, or what this would solve/improve.
Having a changelog helps, most people and automations know to look for changelog.{txt,md} in a repo.
Personally I prefer having it in a file because when it is linked to, it's easier to scan the previous release notes, which in GH releases it takes going up a level and paging through past releases.

**Comment by wooorm** [comment]
> I'm not sure I follow the issue here, or what this would solve/improve.

Small things but: Less stuff in root, less noise in git log.
The bigger thing for me is: whether it’s a file or releases, a changelog is based on a git history but to me has a different history. It’s *outside* the project; about the project. I’m not 100% on how to put this into words but it feels more like how the issue tracker is also not checked in.

> Having a changelog helps, most people and automations know to look for changelog.{txt,md} in a repo.

I do still want to keep a changelog. But people / automations also know to look for releases

> while in GH releases it takes going up a level and paging through past releases.

Taking [`micromark`s releases](https://github.com/micromark/micromark/releases) as an example, how is that harder / going up a level?

**Comment by ChristianMurphy** [comment]
> I’m not 100% on how to put this into words but it feels more like how the issue tracker is also not checked in.

That's fair.
The challenge is that releases currently don't really have a concept of draft release notes, which can be useful for larger/major releases.

> Taking micromarks releases as an example, how is that harder / going up a level?

Taking micromark as an example, it's not, there aren't enough releases for it to be a challenge :slightly_smiling_face: 
But taking remark as an example https://github.com/remarkjs/remark/releases, trying to compare remark 13 to remark 12 (or earlier) is a pain, because they are several pages apart.

**Comment by wooorm** [comment]
I do agree that releases aren’t great for beta release lines or monorepos, which are both true for remark, but luckily not here.
The more versions you have, the harder it becomes to compare. E.g., this project’s differences between [4 and 5](https://github.com/remarkjs/react-markdown/blob/main/changelog.md#change-log) are also pretty far apart — whether it’s in a file or on GH Releases

**Comment by ChristianMurphy** [comment]
In a change log, one can search for the release number with `ctrl + f`, in github releases the only option is to go to each page until a release is found :man_shrugging:

**Comment by wooorm** [comment]
I sort of get that, but that also means the files becomes unmanageable: lots of projects that do have a changelog file start removing things after a while, e.g., post a *See the changelog for version 4 here*. How often do you really want to <kbd>CMD+F</kbd> to see 20 versions back?

**Comment by ChristianMurphy** [comment]
Even so, taking an example of that, like how Node splits up changelogs: https://github.com/nodejs/node/tree/master/doc/changelogs
It's easier to know to look in CHANGELOG_V10, for v10 notes, that to page through to release page ??? to find the notes.

**Comment by wooorm** [comment]
Alright!
