### ISSUE TITLE
Add type tests, `types/` folder

### ISSUE THREAD

**Issue by wooorm** [remarkjs/react-markdown#482]
### Subject of the feature

Types are not checked at all. They’re in the root.

### Problem

Clean, test

**Comment by wooorm** [comment]
ps @ChristianMurphy I think you added in types/unist as a dep, but it isn’t used I believe

**Comment by ChristianMurphy** [comment]
It may or may not be needed.
IIRC I added it because there was a warning/error if it wasn't added.
Checking the types with dtslint and type tests would confirm if it is still needed or not.

**Comment by wooorm** [comment]
Could you take this one on? I haven't dealt with jsx in type tests and am sure what to do about the with-html file in root

**Comment by ChristianMurphy** [comment]
There are non-index d.ts files?
That may make moving the typings into a `types` folder tricky, the rules around non-index files with typings in a different folder than the source file are rather complex.
That's why other unified projects like https://github.com/syntax-tree/unist-util-is have opted to forgo a `types` folder.

Type tests, I can quickly take on, the only difference with jsx tests is the extension needs to be `tsx` instead of `ts`.
Moving the typings out of root into types may take a bit longer to research, setup, and validate (if it is supported at all on the minimum typescript version).

**Comment by wooorm** [comment]
Main thing for me is having ’em tested; if possible to clean, we can do it later, or in 6
