### ISSUE TITLE
The combination Html + MarkDown don't parse MarkDown

### ISSUE THREAD

**Issue by jud3v** [remarkjs/react-markdown#488]
### Subject of the issue
The combination Html + MarkDown don't parse MarkDown

Describe your issue here.

The combination Html + MarkDown don't parse MarkDown

### Your environment

*   **OS**: OS X 
*   **Packages**: react-markdown 
*   **Env**: 
- node: 12.18.4
- yarn: 1.22.10
- react: 16.X

### Steps to reproduce

`use this:`

```txt
<div class="flex justify-center">
      ![images n°45](http://localhost:8000/api/images/sDp3TYoOKXCdEEJnKWfA8MeAroUSAudG4G6CAyju.jpeg?w=200&h=200)
<div>
```

> this don't be parsed:
```txt
![images n°45](http://localhost:8000/api/images/sDp3TYoOKXCdEEJnKWfA8MeAroUSAudG4G6CAyju.jpeg?w=200&h=200)
```

This is normal the markdown inside Html doesn't be parsed ?

### Expected behavior

> Position of images

What should happen?

> markdown don't be parsed inside Html

**Comment by wooorm** [comment]
This is a feature of markdown, take a look at how it renders in [CommonMark](https://spec.commonmark.org/dingus/?text=%3Cdiv%20class%3D%22flex%20justify-center%22%3E%0A%20%20%20%20%20%20!%5Bimages%20n°45%5D(http%3A%2F%2Flocalhost%3A8000%2Fapi%2Fimages%2FsDp3TYoOKXCdEEJnKWfA8MeAroUSAudG4G6CAyju.jpeg%3Fw%3D200%26h%3D200)%0A%3Cdiv%3E). Or here on GitHub even:

<div class="flex justify-center">
      ![images n°45](http://localhost:8000/api/images/sDp3TYoOKXCdEEJnKWfA8MeAroUSAudG4G6CAyju.jpeg?w=200&h=200)
<div>

Do get your desired output, place blank lines between HTML and markdown, *and* make sure to remove the indentation (otherwise it would turn into an indentted code block)

```markdown
<div class="flex justify-center">

![images n°45](http://localhost:8000/api/images/sDp3TYoOKXCdEEJnKWfA8MeAroUSAudG4G6CAyju.jpeg?w=200&h=200)

<div>
```

**Comment by jud3v** [comment]
Thank you 👍
