### ISSUE TITLE
IE11 Support - Arrow functions ends up in final bundle

### ISSUE THREAD

**Issue by klarstrup** [remarkjs/react-markdown#499]
I intend to expand on this issue tomorrow but just to put it down now

Between 4.3.1 and 5.0.0 something happened either to the bundling of this project or to some dependency of it, that leads to an untranspiled arrow functions ending up in the final bundle arrow functions and all when consumed with Webpack 4

Additionally I think you'd do well to add `"browser": "react-markdown.min.js"` to package.json, but this was also not present in 4.3.1.

**Comment by ChristianMurphy** [comment]
@klarstrup you can check out what is in react-markdown here: https://unpkg.com/react-markdown@5.0.2/react-markdown.min.js there aren't any arrow functions in the bundle.

**Comment by ChristianMurphy** [comment]
similar to https://github.com/remarkjs/react-markdown/issues/359 if you need IE 11 support you are welcome to add it though your webpack configuration.
The project does not plan for force all adopters to have IE polyfills.

**Comment by wooorm** [comment]
@ChristianMurphy It is instead correct that there is ES++ in react-markdown. Not directly, but in a dependency in unified: https://github.com/sindresorhus/is-plain-obj/blob/master/index.js. The UMD bundle handles ES++ in its dependencies, but if you’re using webpack or whatever you’re not getting the UMD bundle.

@klarstrup I am personally sad that this is the case, but it’s also not feasible to build projects without dependencies.
You’ll have to deal with ES++ features in your dependencies.

**Comment by klarstrup** [comment]
What is in the way of adding the UMD bundle on `pkg.browser`? Would
something else break? I can make the PR

**Comment by wooorm** [comment]
That is not what the [browser field](https://github.com/defunctzombie/package-browser-field-spec#overview) is for. Abusing the field to add UMD bundles will result in more data sent to browsers, and more memory used in Node, because files are duplicated when you yourself or other dependencies use any of our [dependencies](https://github.com/remarkjs/react-markdown/blob/6e38dd343ef653b6c5246625ac3476ffd94d0ebc/package.json#L42-L49), or transient ones.

Again, you’ll have to deal with ES++ features in your dependencies in your bundler yourself. If you duckduckgo/google for “IE11 webpack” (or whatever bundler you like), you’ll find how to do that.
