### ISSUE TITLE
Possible to get the HTML output instead of it being rendered?

### ISSUE THREAD

**Issue by ahmetskilinc** [remarkjs/react-markdown#536]
I'm not sure if this has been posted.

I want to be able to get the RAW html that is output so I can maybe copy it and use it elsewhere. Say for instance a Markdown editor, where a user can write markdown, and it is output to the page by react-markdown. Is it possible to get the HTML instead of going to inspect element?

**Comment by ChristianMurphy** [comment]
Short answer:
Is possible to get HTML from [unified](https://github.com/unifiedjs/unified)/[micromark](https://github.com/micromark/micromark)? (the underlying libraries for react-remark and maintained by the same team) **yes**
Will `react-markdown` specifically support it, **no**


---

Context:

[Micromark](https://github.com/micromark/micromark) is the underlying markdown parser used in react-markdown, it can be used directly to take markdown to HTML.
[Remark](https://github.com/remarkjs/remark) and [Rehype](https://github.com/rehypejs/rehype) builds on Micromark, allowing content to be [transformed with Plugins](https://unifiedjs.com/learn/) along the way.
`react-markdown` builds on remark (and [soon rehype](https://github.com/remarkjs/react-markdown/issues/427)) to output React components specifically.

Generating HTML is a non-goal for react-markdown specifically, because it, as the name implies, targets React.
However other libraries (micromark, remark, and rehype) in the same organization, with the same maintainers, are designed to do what you are looking for and go from markdown to HTML.

---

Examples of how to use Micromark and Remark+Rehype:
Micromark: https://codesandbox.io/s/micromark-debug-y9vz3
Remark-rehype: https://codesandbox.io/s/remark-rehype-debug-4cz8v

**Comment by ahmetskilinc** [comment]
@ChristianMurphy Okay. Thank you. I managed to do exactly what I wanted to do using Micromark!
