### ISSUE TITLE
Add some EventListeners or CallbackFunctions to this Compoent

### ISSUE THREAD

**Issue by Polaris-tl** [remarkjs/react-markdown#553]
### Subject of the feature

I need to get the rendered dom information to generate some data.the best way is do this work after the MarkDown Component finish render.But it seems that there is no such feature in this Component.anyway ,It's really a great React Compent 

### Expected behavior

there is a function passed into this compoent and call this function after the markdown is rendered.

**Comment by ChristianMurphy** [comment]
> do this work after the MarkDown Component finish render.But it seems that there is no such feature in this Component

I'm not sure this makes sense in `react-markdown`.
Mainly because "finished rendering" is a fuzzy concept in react and largely out of control of `react-markdown`.
The callback could be fired as a layout effect, after render has happened, but before initial point of the new state.
The callback could be fired as an effect, after render and after paint.
The callback could attempt to fire after all effects have settled (which would be a heuristic since any number of side effects could happen and the timing can be outside even React's control).

I'm not sure any of the above are what you are looking for.
Reading between the lines of

> I need to get the rendered dom information to generate some data.the best way is do this work after the MarkDown Component finish render

It sounds like you want to wait for a specific DOM reference to be ready on the page?
Is that accurate?

If so, life cycle would likely make things more complex than creating a custom component/renderer https://github.com/remarkjs/react-markdown#use-custom-renderers-syntax-highlight
And inside that component attaching a `ref` to the DOM element you need to wait for/access https://reactjs.org/docs/refs-and-the-dom.html
And generating the data within the custom element.

**Comment by ChristianMurphy** [comment]
@Polaris-tl thoughts? :thought_balloon:

**Comment by ChristianMurphy** [comment]
I'll take silence as it resolved the issue, if you have follow up questions feel free to ask on the discussion forum https://github.com/remarkjs/remark/discussions
