### ISSUE TITLE
Error: Not supported with Next.js

### ISSUE THREAD

**Issue by yezovskih** [remarkjs/react-markdown#646]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

^7.0.1

### Steps to reproduce

1) Create a new project with `npx create-next-app --typescript` and run `npm install react-markdown`
2) Edit `index.tsx` file
```
import type { NextPage } from 'next'
import React from 'react';
import ReactMarkdown from 'react-markdown';


const Home: NextPage = () => {
  return <ReactMarkdown># Hello, *world*!</ReactMarkdown>;
}

export default Home
```
3) Add line to `next.config.js`
```
experimental: { esmExternals: true }
```
4) Open in browser and see an error

### Expected behavior

I can see rendered markdown

### Actual behavior

I see error
<img width="1274" alt="error" src="https://user-images.githubusercontent.com/13916109/132880412-ca67f93b-88a0-46f9-9c67-27bf6e78e1b4.png">

### Runtime

Node v14

### Package manager

npm v7

### OS

macOS

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
Hey! Sorry you ran into trouble!

`react-markdown` is behaving as it should be: fully ESM compliant, and used by many.
Hence I’ll close this issue as it’s not something to be fixed here.

Next and TS, however, are not behaving. Your issue here looks like a project Next setup, but I infer from your error message that you’re using TS, and that leads me to think that that isn’t set up properly.
See https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#im-having-problems-with-esm-and-typescript for more information on ESM and TS.

**Comment by J3tto** [comment]
@yezovskih  I'm experiencing the same issue with nextjs did you find a solution?

**Comment by yezovskih** [comment]
@J3tto Yes, I found a workaround on how to make it work with Next.js [here].(https://github.com/vercel/next.js/issues/25454#issuecomment-905643343))
But I decided to use `next-mdx-remote` for markdown [from article](https://nextjs.org/blog/markdown)

**Comment by lbittner-pdftron** [comment]
+1

Terrible decision by the author to only support esm. `next-mdx-remote` works for me as well 👍
