### ISSUE TITLE
Usage of main field instead of module in package.json

### ISSUE THREAD

**Issue by gmukul01** [remarkjs/react-markdown#650]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7

### Steps to reproduce

Use Rollup to bundle this package.

### Expected behavior

Since `react-markdown` is `ESM` we should use `module` field in `package.json`
[Rollup Wiki](https://github.com/rollup/rollup/wiki/pkg.module)
[Webpack docs](https://webpack.js.org/guides/author-libraries/#final-steps)

### Actual behavior

If we use any rollup bundler to bundle this package then due to the `main` field in package.json rollup consider it as `CJS` instead of `ESM`.  And due to which in final bundle rollup uses `require` to import the esm package.

### Runtime

Node v14

### Package manager

npm v6

### OS

macOS

### Build and bundle tools

Rollup

**Comment by wooorm** [comment]
hi there Mukul!

The behavior you describe, the current behavior, is intended.
This package is intentionally ESM only, and intentionally does not have a `module` field, because `module` fields are not standard. This is documented in the rollup and webpack links you mentioned.

> If we use any rollup bundler to bundle this package then due to the main field in package.json rollup consider it as CJS instead of ESM. And due to which in final bundle rollup uses require to import the esm package.

This statement is incorrect. There is a `type: module` field, which is the standard way of saying a package is ESM. Both Rollup and webpack understand that field.

For more information, please see the changelog, and the reference on ESM therein: https://github.com/remarkjs/react-markdown/blob/main/changelog.md#700---2021-08-13.

**Comment by wooorm** [comment]
You are asking rollup to create a CJS bundle, and it seems to do that.
But, this project can’t be used in CJS (except if you’re `import()`ing it with a dynamic expression)

**Comment by gmukul01** [comment]
@wooorm Thank you so much for all the information. :)
