### ISSUE TITLE
Images are rendered in a p tag.

### ISSUE THREAD

**Issue by byrneml** [remarkjs/react-markdown#673]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.0

### Link to runnable example

https://codesandbox.io/s/chakra-ui-header-forked-5xk35h?file=/src/index.js

### Steps to reproduce

Install Chakra UI and create a basic instance of react-markdown. Create markdown variable with multiple images.

### Expected behavior

Images should be rendered side-by-side, such as in [this readme:](https://github.com/fMeow/maybe-async-rs/blob/main/README.md)

### Actual behavior

Instead of being rendered side by side, they are stacked. This seems like an override in the Chakra UI theme.

### Runtime

Node v16

### Package manager

yarn 2

### OS

Windows

### Build and bundle tools

Create React App

**Comment by ChristianMurphy** [comment]
Commonmark wraps paragraphs in a `<p>` tag, this is standard and expected.

You can even remove the paragraph with `remark-unwrap-images` https://codesandbox.io/s/chakra-ui-header-forked-y8k7xi?file=/src/index.js and Chakra still renders the images in a block layout.

The issue here is how Charka changes the layout, for example removing the Charka styles results in a normal render: https://codesandbox.io/s/chakra-ui-header-forked-o3m0kz?file=/src/index.js

This is something which you need to fix in your stylesheet/theme.
If you have questions or concerns with how Charka styles images, it is something you should ask the Charka community about https://github.com/chakra-ui/chakra-ui/discussions

**Comment by stoplion** [comment]
List items are wrapped in paragraph too.

**Comment by ChristianMurphy** [comment]
@stoplion this question is about images, if you have a question about list items open a new thread with some additional context on what you tried, what you are seeing, and what you expect at https://github.com/orgs/remarkjs/discussions
