### ISSUE TITLE
Failed to execute 'createElement' on 'Document': The tag name provided ('b<') is not a valid name

### ISSUE THREAD

**Issue by Tasin5541** [remarkjs/react-markdown#716]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown: 8.0.3, rehype-raw: 6.1.1, remark-gfm: 3.0.1

### Steps to reproduce

I am using React-markdown to generate html on the go by typing html code in a panel and showing live preview through react-markdown. Whenever I input a wrong tag (unfinished), I get this error and the whole screen turns white because of the way react handles unhandled runtime errors.

Input an invalid html tag to reproduce

```
const value="<p><b</p>";
<ReactMarkdown children={value} rehypePlugins={[rehypeRaw]} remarkPlugins={[remarkGfm]} />
```

### Expected behavior

The expected behavior is to:
- have a way of catching this type of error and showing them inside react-markdown, or
- just ignore invalid tags and show them as string

### Actual behavior

Getting the following error:

Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('b<') is not a valid name.

### Runtime

Node v16

### Package manager

yarn 2

### OS

Windows

### Build and bundle tools

Vite

**Comment by wooorm** [comment]
This behavior is according to the HTML and DOM spec. You can try that HTML in a browser console:

```
> document.body.innerHTML = "<p><b</p>"
< "<p><b</p>"
> document.body.innerHTML
< "<p><b< p=\"\"></b<></p>"
> document.body.firstElementChild
< <p>…</p>
> document.body.firstElementChild.firstElementChild
< <b< p></b<>
> document.body.firstElementChild.firstElementChild.nodeName
< "B<"
> document.body.firstElementChild.firstElementChild.attributes
< NamedNodeMap = $6
0: p
length: 1
p: p
NamedNodeMap Prototype
> document.createElement('B<')
< InvalidCharacterError: The string contains invalid characters.
```

For your expectations:

- You can likely perform expectation 1 yourself in the standard way that React supports it: use error boundaries: https://reactjs.org/docs/error-boundaries.html
- You can somewhat perform expectation 2 yourself, you can walk the AST, check which elements React can’t handle (e.g., tag name must match `[a-zA-Z][-a-zA-Z0-9]*` or so, simplified example), in which case you replace it with `<pre><code>xxx</code></pre>`, where `xxx` is replaced by `toHtml(node)`, where `node` is the AST you want to serialize, and `toHtml` comes from https://github.com/syntax-tree/hast-util-to-html.

I’ll close this because a) this is all according to specs, b) React has a standard way of handling errors. It’s also c) a rather niche case, you mention “on the go by typing html code in a panel”, this project isn’t really an on-the-go HTML parser, there are better solutions for that out there, and it might be better not to use React at all for it.
