### ISSUE TITLE
Use rollup&&react to build the project, but report an error when introducing the react-markdown build

### ISSUE THREAD

**Issue by manongguai** [remarkjs/react-markdown#724]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.4

### Steps to reproduce

<img width="904" alt="image" src="https://user-images.githubusercontent.com/58075959/212843716-5d61f281-f56c-4209-a906-ddcb10bf4327.png">

Just import ，
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/58075959/212843999-6f0db0de-8689-444a-bde0-28545b8d0f8e.png">

### Expected behavior

I want to know the cause or solution of this problem

### Actual behavior

null

### Runtime

Node v14

### Package manager

npm 6

### OS

macOS

### Build and bundle tools

Rollup

**Comment by Murderlon** [comment]
I'm not sure what's going on, but my gut feeling says the closure compiler can't handle ESM (this is an ESM-only package). If that's the case, that's not something we can help with.

**Comment by remcohaszing** [comment]
The error points to an optional catch binding. It looks like (your version of) Google Clojure can’t handle that.

You may need to update your tooling or compile the code somewhere in your pipeline using [`@babel/plugin-proposal-optional-catch-binding`](https://babeljs.io/docs/en/babel-plugin-proposal-optional-catch-binding).

**Comment by wooorm** [comment]
The cause is optional catch binding support, which seems to be in closure compiler for 4 years already: https://github.com/google/closure-compiler/commits/master/src/com/google/javascript/jscomp/RewriteCatchWithNoBinding.java.
The solution is to use a more recent version should support it, or, depending how you use 

Also looks like you’re using it through `rollup-plugin-closure-compiler`, which has a pretty old dependency on it: https://github.com/ampproject/rollup-plugin-closure-compiler/blob/7ec95e00d7cc08e9fb168e0eb5a3e2ff66a0d5d7/package.json#L42. Perhaps there are more up to date alternatives.

**Comment by manongguai** [comment]
Thank you very much. I probably know how to deal with it
