### ISSUE TITLE
Next.js hydration errors #425 #418 #423 when the markdown is too long

### ISSUE THREAD

**Issue by rubby-c** [remarkjs/react-markdown#727]
### Initial checklist

- [x] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

^8.0.5

### Link to runnable example

Code is below.

### Steps to reproduce

I have a Next.js app with a dynamic route and a MongoDB client fetching data from an external database as such:

```js

// mongodb.ts

import { MongoClient } from 'mongodb';

if (!process.env.MONGODB_URI) {
    throw new Error('Invalid environment variable: "MONGODB_URI"');
}

const uri = process.env.MONGODB_URI;
const options = {};

let client;
let Promise: Promise<MongoClient>;

if (!process.env.MONGODB_URI) {
    throw new Error('Please add your Mongo URI to .env.local');
}

if (process.env.NODE_ENV === 'development') {
    let globalWithMongo = global as typeof globalThis & {
        _mongoClientPromise: Promise<MongoClient>
    }

    if (!globalWithMongo._mongoClientPromise) {
        client = new MongoClient(uri, options);
        globalWithMongo._mongoClientPromise = client.connect();
    }

    Promise = globalWithMongo._mongoClientPromise;
} else {
    client = new MongoClient(uri, options);
    Promise = client.connect();
}

export default Promise;

```

``` js
// [post].js

import ReactMarkdown from 'react-markdown'
import { Box } from '@chakra-ui/react'

const Post = ({ found, post }) => {
    return (
        <>
            {found ? <Box mt={4} itemProp='text'>
                <ReactMarkdown
                    className='article-text'>
                    {post.text}
                </ReactMarkdown>
            </Box> : <h1>Not found!</h1>}
        </>
    );
}

export async function getServerSideProps(context) {
    if (!context.query.post) {
        return;
    }

    const client = await Promise;

    const post = await client.db('db_name')
        .collection('posts')
        .findOne({ _id: context.query.post });

    return {
        props: { found: post !== null, post: post }
    }
}
```

React version: ^18.2.0
Next.js version: ^13.1.6
NPM version: 9.1.2

### Expected behavior

It should just work properly.

### Actual behavior

The errors only appear in production, on a Linux server, and only after the markdown is too long. The errors happen in this order:
[once] 425
[depends on text length, the longer it is, the more errors] 418
[once] 423

I've manually tried removing text line by line and at one point the errors just stops appearing.

![image](https://user-images.githubusercontent.com/80776684/218250516-1be40b74-d00e-4989-9cda-afa743394fd5.png)

### Runtime

Node v16

### Package manager

Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
Welcome @rubby-c!
Sorry you ran into a spot of trouble.

There isn't enough information for this to be actionable, or even debugged.
Could you create a minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example
With a focus on:
* Reducing dependencies to eliminate:
   * MongoDB, instead using static content
   * ChakraUI, instead using plain content
   * potentially even ReactMarkdown, does the issue occur in next with long content period, not just with markdown rendered content
* Sharing the example in a way other can also run it, consider using a sandbox like https://next.new
* If it does turn out to be markdown related, isolate _what_ in the markdown specifically is the issue, for example:
   * is it the number of constructs like bold, italic, or links?
   * is it the length of text, just plain text without constructs?
   * is it time related, not specific to length or constructs, but anything which takes some number of milliseconds crashes?

---

Some general ideas without being able to replicate the issue.
Take a look at the previous next.js related questions https://github.com/remarkjs/react-markdown/issues?q=is%3Aissue+next.js+is%3Aclosed and https://github.com/vercel/next.js/discussions?discussions_q=react-markdown others may have run into the same issue, provided additional context, and found a fix.
Consider opening a discussion in the Next community https://github.com/vercel/next.js/discussions since the error is a Next.js error.
`react-markdown` happens to be on the page, but it remains unclear if it is actually the root cause.

**Comment by rubby-c** [comment]
Figured it out, after 3 days of pain it turns out it was the last thing I'd expect - Cloudflare! Minifying somehow messed up the markdown html.. Thanks a lot for suggesting https://next.new, I got the idea to check Cloudflare after I couldn't reproduce the issue on it.
