### ISSUE TITLE
Does it has preview mode ? how to getValues ? 

### ISSUE THREAD

**Issue by vaynevayne** [remarkjs/react-markdown#728]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

it seems that markdown only supports editing, not saving, and there is no preview mode. I don't understand why it has so many stars

### Expected behavior

it seems that markdown only supports editing, not saving, and there is no preview mode. I don't understand why it has so many stars

### Actual behavior

it seems that markdown only supports editing, not saving, and there is no preview mode. I don't understand why it has so many stars

**Comment by remcohaszing** [comment]
Hello, and welcome to GitHub.

GitHub is a place where people work together to build software which often can be used free of charge. This includes `react-markdown`. This project has many stars, because it is useful and many people like it. Opening an issue just to question this, is disrespectful.

When creating this issue, you selected the `Bug report` template, but you did not fill in the template, nor did you report a bug.
