### ISSUE TITLE
Customizing component by wrapping img with a div results in a Next.JS hydration error

### ISSUE THREAD

**Issue by RobinBertilsson** [remarkjs/react-markdown#731]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

8.0.5

### Steps to reproduce

https://stackblitz.com/edit/nextjs-hdyjmu?file=pages/index.js

### Expected behavior

When wrapping `img` with a div, you should not get an error

### Actual behavior

When wrapping `img` with a div, it results in a Next.JS hydration error

### Runtime

Node v17, Node v16

### Package manager

npm 8

### OS

Linux, macOS

### Build and bundle tools

Next.js

**Comment by RobinBertilsson** [comment]
It's due to the wrapping `<p>` element, if i instead set it to `p: ({ children }) => <>{children}</>` it does work, but what would be a proper solution to this?

**Comment by ChristianMurphy** [comment]
Yep, create invalid HTML serverside, you get a hydration error clientside.

Taking markdown out of the mix to explain the issue
```html
<p>
  <div>
    <img>
  </div>
</p>
```
is invalid `<div>` cannot appear in `<p>`.
The browser rewrites this to recover, the result becoming:
```html
<p></p>
<div>
  <img>
</div>
<p></p>
```

You can take a look at this plain HTML, in a jsfiddle for an example, inspect the output HTML to see how it's rewritten: https://jsfiddle.net/rb94d2Lz/1/

Trying to force Next.js to render invalid HTML can often result in a hydration error.
The fix is: don't ask Next.js to generate invalid HTML.
