### ISSUE TITLE
peer dep has invalid package.json so certain tools blow up

### ISSUE THREAD

**Issue by lifeiscontent** [remarkjs/react-markdown#766]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark-util-symbol 1.1.0

### Steps to reproduce

because version 1.1.0 didn't have the `default` file it has now in newer version when trying to use `require.resolve("micromark-util-symbol")` Node.js will throw an error

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/lifeiscontent/GitHub/sortxyz/sorthub/node_modules/.pnpm/node_modules/micromark-util-symbol/package.json

Node version 18.x (which isn't an option in the form below)

### Expected behavior

not have Node.js throw an error when using packages from these projects

### Actual behavior

Node.js throw's an error when using `require.resolve("micromark-util-symbol")` which is a dep of react-markdown

### Runtime

Other (please specify in steps to reproduce)

### Package manager

pnpm

### OS

macOS

### Build and bundle tools

Remix

**Comment by ChristianMurphy** [comment]
Hey @lifeiscontent! 👋 
Sorry you ran into a spot of trouble

> because version 1.1.0 didn't have the default file it has now in newer version when trying to use `require.resolve("micromark-util-symbol")`

This doesn't make sense.
1. "version 1.1.0" of what?
2. "default file it has now in newer version" don't lock versions that are incompatible together on your project, upgrade them to the latest version with fixes
3. `require.resolve("micromark-util-symbol")`. Unified, micromark, remark, and react-markdown are all ESM, there are no requires. Consider using import metadata instead of trying to mix module systems https://nodejs.org/api/esm.html#importmetaresolvespecifier-parent

**Comment by remcohaszing** [comment]
It is possible to resolve ESM packages using `require.resolve("micromark-util-symbol")` if the package exports allow it. This works for [`micromark-util-symbol@2.0.0`](https://github.com/micromark/micromark/blob/micromark-util-symbol@2.0.0/packages/micromark-util-symbol/package.json#L33), but not [`micromark-util-symbol@1.1.0`](https://github.com/micromark/micromark/blob/micromark-util-symbol@1.1.0/packages/micromark-util-symbol/package.json#L41-L50). This is ok, as it’s a semver major difference.

It’s not clear to me why the OP ran into this. I don’t think this is an issue with `react-markdown`, but possibly with the user’s project configuration.

**Comment by lifeiscontent** [comment]
@remcohaszing the reason for running into this issue was due to using remix's utils for finding ESM modules to bundle with the server build, here's the remix config:

```js
/** @type {import('@remix-run/dev').AppConfig} */

const { getDependenciesToBundle } = require("@remix-run/dev");
const { flatRoutes } = require("remix-flat-routes");
const serverDependenciesToBundle = getDependenciesToBundle("react-markdown");

module.exports = {
  ignoredRouteFiles: ["**/.*"],
  serverModuleFormat: "cjs",
  tailwind: true,
  future: {
    v2_dev: true,
    v2_errorBoundary: true,
    v2_headers: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
  serverDependenciesToBundle,
  routes(defineRoutes) {
    return flatRoutes("routes", defineRoutes);
  },
};
```

`getDependenciesToBundle` will error due to this issue with micromark-util-symbol@1.1.0 not having a proper package.json so the dependencies never fully resolve from this function

**Comment by remcohaszing** [comment]
`micromark-util-symbol@1.1.0` does have a proper `package.json`. It’s uncommon for a package to not have an export for `"."`, but it is valid.

The real bug is `getDependenciesToBundle` from `@remix-run/dev` doesn’t handle this situation. I suggest creating an issue there.

`micromark-util-symbol@2.0.0` does have an export for `"."`. We’re in the process of updating major versions all across the unified ecosystem. It’s a matter of time until `react-markdown` is updated, which will make the problem go away.

I’m closing this issue, because it’s not about `react-markdown`.

**Comment by lifeiscontent** [comment]
@remcohaszing this issue is present due to node not being able to resolve the package.json and node throwing the error, not the utility remix exposes.

**Comment by remcohaszing** [comment]
Node.js is able to resolve the `package.json`. Remix’x `getDependenciesToBundle` is unable to these somewhat unusual, but valid package exports.
