### ISSUE TITLE
HeadingProps not available since update to 9.0.0

### ISSUE THREAD

**Issue by stvncode** [remarkjs/react-markdown#778]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.0

### Steps to reproduce

import { type HeadingProps } from 'react-markdown/lib/ast-to-react'

### Expected behavior

Work fine 

### Actual behavior

File doesn't exist anymore. Just a index.d.ts

### Runtime

Node v17

### Package manager

pnpm

### OS

macOS

### Build and bundle tools

esbuild, Vite

**Comment by ChristianMurphy** [comment]
Hey @stvncode! 👋 
Sorry you ran into a spot of trouble.

Version 9 intentionally removes access to internal APIs https://github.com/remarkjs/react-markdown/blob/main/changelog.md#900---2023-09-27

Please migrate away from using internals.
If you have a reason you believe it should be a public API, feel free to share and it can be discussed.

**Comment by wooorm** [comment]
> The problem is that i can't type my props in MarkdownHeading with the type from the lib since it doesn't exist anymore. What should i do ?

`HeadingProps` used to exist because it was special to this project.
We don‘t do special things in this project for headings anymore, so it is not needed.
Instead, use your frameworks types: `JSX.IntrinsicElements['h1']` for example.

We also pass one extra prop. `node`. This is typed and documented https://github.com/remarkjs/react-markdown?tab=readme-ov-file#extraprops. You can combine both if wanted (`JSX.IntrinsicElements['h1'] & ExtraProps`)
