### ISSUE TITLE
Does not parse ordered list from markdown correctly, 

### ISSUE THREAD

**Issue by zerogtiger** [remarkjs/react-markdown#806]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

react-markdown (^9.0.0), rehype-raw (^7.0.0)

### Steps to reproduce

Run the following snippet in a suitable JS file: (node version 21.2.0, npm version 10.2.5)
```javascript
    <ReactMarkdown rehypePlugins={[rehypeRaw]} children={'<ol><li>Item 1</li><li>Item 2</li><li>Item 3</li></ol>'} />

```

### Expected behavior

1. Item 1
2. Item 2
3. Item 3

### Actual behavior

&nbsp; item 1
&nbsp; item 2
&nbsp; item 3

### OS

macOS

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
Welcome @zerogtiger! 👋 
Sorry you ran into a spot of trouble.

I can't replicate the issue you describe on the playground page https://remarkjs.github.io/react-markdown/

Are you using Tailwind or another styling library with heavy-handed resets on your page.
The is the most likely root cause?

The second most likely is a mismatch between dependency versions.
Make sure both react markdown and rehype raw are on the latest version.

**Comment by zerogtiger** [comment]
Hey Christian,

Thanks for the quick reply. I am indeed using tailwindcss and have pinpointed the issue thanks to your reminder. It does not have to do with rehype or react-markdown. 

Wishing you a wonderful holiday season!
