### ISSUE TITLE
Why isn't mathInline triggered?

### ISSUE THREAD

**Issue by punkpeye** [remarkjs/react-markdown#866]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I added `import remarkMath from 'remark-math';` to my remark plugins.

I then added a custom component `inlineMath: { console.log('Hello!'); }`

I would expect `inlineMath` to be called when rendering math expression, but it isn't.

What am I missing?

**Comment by wooorm** [comment]
I do not know where you got the word `inlineMath` from. That doesn’t happen.
There’s no code that does what you expect.

Math (“inline” or “block”) uses `<code>` elements.

Keys in components are HTML tag names.

**Comment by mola-molaa** [comment]
I dont know if its the same issue here, what i encountered for example:

``` 
 <ReactMarkdown
      rehypePlugins={[[rehypeMathjax,{
tex: {
    packages: ['base', 'ams', 'html'],
    inlineMath: [
      ['😄', '😄'],
    ],
    processEscapes: true,
    processEnvironments: true,
  },
}]]}
      remarkPlugins={[gfm, [remarkMath]]}
      components={memoComponents}
    >
      {'😄2=1+1😄'}
    </ReactMarkdown>
``` 

above will render paragraph rather than inline math svg;

in fact, i debug hours, found that rehype-mathjax would expect ast has 'math-inline' classanme or something related, then go into mathjax new Tex input logic, otherwise, mathjax's render method not being called at all.

<img width="348" alt="Image" src="https://github.com/user-attachments/assets/2ad8f3a0-a74b-4c7f-8438-c78ea88ea761" />

however, what i expect is that  The inline math custom rules would affect parsed output ast... then make formula render

is there something i am missing, how i able to make my custom line match syntax work?

BTW, react-markdown is GREAT！
